### ISSUE TITLE
Убрать все волшебные строки и числа

### ISSUE THREAD

**Issue by ravilASH** [Drozdov96/Education#1]
По всему проекту в коде не должны появляться цифры непонятного значения -1, 0,  и строки типа 'miss    ' в которых легко ошибиться, все заменить на константы с понятным названием https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant

**Comment by Drozdov96** [comment]
Убрал волшебные строки и числа по всему проекту, включая View.
